### ISSUE TITLE
Alert locker administrator on duplicate application at another library

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#113]
### User story

As a lockers administrator, I would like to see an alert on the locker application list if a student has also applied for a locker at another library, so that I can follow up with the student and let them know that they can only have one.

### Implementation notes, if any

One outstanding question for the stakeholders: should the system allow these duplicate applications in the first place? 

Yes, allow them to be accepted. 

Another point of clarification: how do we determine which applications are "duplicates"?  I'm assuming that if a student applies for a Firestone locker in year 1, then a Lewis locker in year 2, the alert should not show.

Duplicates can be determined by: if the user has an assigned locker already or a non-archived pending application.

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Work-Cycle-Board-571691cab409d8d821b873be/issues/pulibrary/lockers_and_study_spaces/113?planning-poker) with Zenhub @christinach @maxkadel @rladdusaw @sandbergja

**Comment by maxkadel** [comment]
UI issues - may create a mock-up and send it around for ideas / feedback.

**Comment by sandbergja** [comment]
Prototype here: https://xd.adobe.com/view/2d6d8c85-4e15-4c0b-86d1-f7f6124455ee-783e/

**Comment by christinach** [comment]
> Prototype here: https://xd.adobe.com/view/2d6d8c85-4e15-4c0b-86d1-f7f6124455ee-783e/

Looks great to me.

**Comment by maxkadel** [comment]
I like it the prototype a lot! Especially the click to copy applicant email address. 

Do you think it would be possible and helpful for the Firestone administrator to be able to view the Lewis application, and vice versa?

Also, this might just be a semantic question - for this example, does the user have 2 total applications? If so, I would think of that as "1 duplicate" application, rather than 2 duplicates (so number of duplicates would be something like total number of matching applications minus 1).
