### ISSUE TITLE
Flash message ux improvements

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lockers_and_study_spaces#195]
### Current display

Flash messages show in plain text.  They don't disappear unless you reload the page, and there is no way for the user to dismiss them.  They don't have much styling.

### Desired display

To make them less intrusive, flash messages should disappear after a certain amount of time (but be sure to allow plenty of time for the user to notice them and read them) or the user can dismiss them with a close button.

To draw attention to them more, they should have more prominent styling.

### Acceptance criteria

- [x] Flash messages disappear after a certain amount of time
- [x] Flash messages have more prominent styling
- [x] I can successfully use the flash messages with Voice Over in Safari.  In particular, the flash messages don't disappear before they are read. If there is a close button, it's possible to use the button with VoiceOver.
- [x] I have checked the restyled flash messages using one of the following browser extensions and confirmed that the new style and behavior do not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

**Comment by sandbergja** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-Work-Cycle-Board-571691cab409d8d821b873be/issues/pulibrary/lockers_and_study_spaces/195?planning-poker) with Zenhub @maxkadel @regineheberlein @rladdusaw @kevinreiss

**Comment by rladdusaw** [comment]
I've implemented this with https://github.com/pulibrary/lockers_and_study_spaces/pull/223 but the flash messages only last 2 seconds and are difficult to navigate to before they close with a screen reader.

Lux does not allow you to set the length of time before auto-clearing the alert and a PR would be needed to allow more time to navigate to them. 

Since the current implementation just embeds the text on the page, a dismissible alert could be an interim solution that would still be a significant improvement to the ux.
